hundsun-ui/h_ui

.gitignore, example/views/Select.vue, src/components/Select/Select.vue, src/style/components/select.scss
1. 修改h-tag的定位和其他显示问题
2. 单选@on-change函数的传入参数不再转义
=> [Select] h-tag modify and single-select @on-change params modify

example/views/DatePicker.vue
=> showlong example

example/views/Select.vue, src/components/Select/Select.vue
props filterable： true
1. 选择一个 option
2. 清空选择
3. 再次选择该 option
下拉框不消失问题
=> 修复：props filterable 情况下，下拉框不消失问题

example/views/SimpleSelect.vue, src/components/SimpleSelect/Block.vue
[simple-select] 
1. 修复内部数据监听在特殊情况下会失效
=> TS0097-FIX01

src/components/SelectTable/SelectTable.vue
[simple-select] 
1. 多选enter控制和选值校准
=> TS0097-FIX02

.eslintrc.js, .gitignore, .npmignore, example/views/Form.vue, example/views/Input.vue, example/views/InputNumber.vue, example/views/Typefield.vue, src/components/Form/Form.vue, src/components/Form/FormItem.vue, src/components/Input/Input.vue, src/components/InputNumber/InputNumber.vue, src/components/Typefield/Typefield.vue, src/util/tools.js
- [input]添加type=number支持
- [inputNumber]添加`notScientificNotation`属性，表示不使用科学计数法显示输入
- [form]添加 resetValidate 和 resetValidateField 方法，用于重置全部校验结果和重置单个校验结果
=> 2019 04 04

.eslintrc.js, example/router/index.js, example/views/Home.vue, example/views/SimpleSelect.vue, src/components/Form/Form.vue, src/components/SelectTable/SelectTable.vue, src/components/SimpleSelect/Block.vue, src/components/SimpleSelect/SimpleSelect.js, src/components/SimpleSelect/index.js, src/directives/clickoutside.js, src/mixins/emitter.js, src/mixins/locale.js, src/util/dom.js
- [simple-select]<TS> 有默认值时上下键不生效
- [simple-select/select-table] 隐藏下拉框时过滤条件存在，再打开却不再过滤
- [simple-select]<TS201904080439> 赋初值 + remoteMethod 存在值更新问题
- [simple-select] 修复remoteMethod情况下selete tag label显示值错误问题
- [simple-select] 修复关闭弹框过滤条件未重置问题
- [simple-select] 修复远程搜索只有一个值时，translate3D位置问题
=> 2019 04 16

example/views/SimpleSelect.vue, src/components/SelectTable/SelectTable.vue
[simple-select] 修改 multiple + remote tag 显示逻辑
=> 2019-04-16

example/router/index.js, example/views/GroupTable.vue, src/components/Form/Form.vue, src/components/Form/FormItem.vue, src/components/Form/validate.js, src/util/tools.js
=> 2019-04-28

example/router/index.js, example/views/Checkbox.vue, example/views/Select.vue, example/views/SelectTable.vue, example/views/SimpleTable.vue, src/components/SelectTable/Option.vue, src/components/SelectTable/SelectTable.vue, src/components/SimpleTable/SimpleTable.vue, src/components/SimpleTable/Table-cell.vue, src/components/Table/Cell.vue, src/components/Typefield/Typefield.vue, src/style/components/selectTable.scss, src/style/mixins/select.scss
- [simple-select] 修改 selectedSingle 的赋值判断
- [select] select-item 字体去掉 important
- [table & select-table & simple-table] 添加 checkbox 大小控制
- [type-field] 添加属性 positive 表示是否只允许正数，默认 false
=> 2019-05-09

example/router/index.js, src/components/EditGird/Cell.vue, src/components/MsgBox/MsgBox.vue, src/components/MsgBox/confirm.js
- [msgbox] 修复点击右上角叉号实例未移除问题（js 调用时）
- [group-table] 新增 radio 选中（部分代码）
=> 2019-05-21.3

example/router/index.js, example/views/TreeGird.vue, src/components/SimpleSelect/Block.vue, src/style/components/select-block.scss
- [simple-select] 添加多列表头、对齐、过滤
=> 2019-05-30.1

example/router/index.js, example/views/TreeGird.vue, src/components/SelectTable/SelectTable.vue, src/components/SimpleSelect/Block.vue, src/style/components/select-block.scss
- [simple-select] 添加 focusInit 属性，用于设置初始 focus 的选项
=> 2019-05-30.2

example/views/MsgBox.vue, src/components/MsgBox/MsgBox.vue
1. add a new prop "lazyload".
2. add a new event "on-open".
=> MsgBox: new feature

example/views/Select.vue, src/components/Select/Dropdown.vue, src/components/Select/Select.vue, src/components/SimpleSelect/Block.vue
- [simple-select] 修复不设置 showHeader 只设置 showCol 时多列间距问题
- [select] 修复 autoPlacement 不生效问题
=> 2019-05-30.3

src/components/SelectTable/SelectTable.vue, src/components/SimpleSelect/Block.vue, src/style/components/select-block.scss
- [simple-select] 修复多列过滤后不能选通过上下键和回车选择问题、修复多选框对齐问题、修复多列表头颜色问题
=> 2019-05-30.4

example/router/index.js, example/views/Select.vue, src/components/EditGird/Cell.vue, src/components/EditGird/type/edit.js, src/components/Form/validate.js, src/components/Select/Select.vue
- [select] 优化 autoPlacement
- [edit-grid] 添加 validate 校验方法，添加 column.rule 允许校验数组
=> 2019-06-06

src/components/Typefield/Typefield.vue
=> 2019-06-06.1

example/router/index.js, src/components/EditGird/Cell.vue, src/components/EditGird/Gird-body.vue, src/components/EditGird/Gird-table.vue, src/components/EditGird/Tree-table.vue, src/components/EditGird/expand.js, src/components/FileExport/FileExport.vue, src/components/Radio/RadioGroup.vue, src/style/components/editgird.scss, src/style/components/select-block.scss
- [edit-grid] 修复校验时错误提示显示在表格外部问题
- [tree-grid] 第一列设置 ellipsis 时使用 render 也能超长显示省略号
- [tree-grid] 添加 column.checked 默认选中机制
- [radio-group] 添加 focus / blur 函数
=> 2019-06-13

src/components/SimpleTable/SimpleTable.vue
=> SimpletTable: bugfix

example/views/Calendar.vue, src/components/Calendar/Calendar.vue, src/components/Calendar/DateCell.vue, src/components/Calendar/MonthView.vue, src/components/Radio/RadioGroup.vue, src/components/Schedule/Schedule.vue, src/style/components/calendar.scss, src/style/components/schedule.scss, src/util/tools.js
- [calendar] 添加 badges 属性和点击事件
=> 2019-06-13.1

src/components/SelectTable/SelectTable.vue
Fix the bug that the option list wouldn't show up when user inputs query words.
=> SimpleSelect: bugfix

src/components/SimpleTable/SimpleTable.vue, src/components/Table/Table.vue
table and simpletable add dataCheckedProp
=>  add dataCheckedProp

src/components/Table/Table.vue
support for getting all selected filters on every column by invoking getFilters
=> Table: new method "getFilters"

src/components/DatePicker/picker.vue, src/components/EditGird/Cell.vue, src/components/FileExport/FileExport.vue, src/components/Select/Dropdown.vue, src/components/SimpleSelect/Block.vue, src/components/SimpleTable/Cell.vue, src/components/SimpleTable/SimpleTable.vue
- [file-export] 添加 xls xlsx 类型限制说明; 
- [date-picker] autoPlacement 逻辑修改; 
- [edit-grid] type 值为 date / select 时默认添加 autoPlacement 属性; 
- [simple-table] 值更新滚动条跳动问题修复
=> 2019-06-20

src/components/Form/FormItem.vue, src/components/Page/Options.vue, src/components/Page/Page.vue, src/components/Typefield/Typefield.vue, src/style/components/page.scss
fixed validate bind event ,
update typefield,
page add showReload
=> commit hui_v1.0.41

example/router/index.js, src/components/DatePicker/picker.vue, src/components/EditGird/Cell.vue, src/components/SimpleSelect/Block.vue
- [simple-table]/[simple-select] 缺陷修复
=> 2019-06-20.1

src/components/SelectTable/SelectTable.vue, src/components/SimpleSelect/Block.vue
=> 2019-06-20.2

example/views/Select.vue, src/components/EditGird/Gird-body.vue, src/components/EditGird/Tree-table.vue, src/style/components/select-block.scss, src/style/components/select.scss
- [tree-gird] 添加 row.hidden 属性
- [select / simple-select] hideMult 属性样式更改
=> 2019-06-27

example/App.vue, example/views/Upload.vue, src/components/Upload/Upload.vue
=> Upload: support for mergeHook

example/views/TreeGird.vue, src/components/EditGird/Gird-body.vue, src/components/EditGird/Gird-table.vue, src/components/EditGird/mixin.js, src/style/components/editgird.scss, src/util/tools.js
=> TreeGrid: support for stripe

src/components/DatePicker/picker.vue, src/components/FileExport/FileExport.vue, src/components/Form/FormItem.vue, src/components/SimpleSelect/Block.vue, src/components/Table/Table.vue
- [date-picker] autoPlacement 左右空间自适应;
- [form-item]  blur / change 监听事件可携带参数; 
- [table] on-move 事件返回值修改; 
- [simple-select] 修复下拉最后一项在部分系统会闪动一下问题
=> 2019-07-04

src/components/AsycTreeGird/Cell.vue, src/components/AsycTreeGird/Gird-body.vue, src/components/AsycTreeGird/Gird-table.vue, src/components/AsycTreeGird/Table-tr.vue
AsyncTreeGrid: trigger on-row-dblclick event while dblclicking on the row
=> AsyncTreeGrid: trigger on-row-dblclick event

src/components/Input/Input.vue, src/components/Table/Table.vue
=> update input and table

src/components/Calendar/Calendar.vue
=> fixed calendar

src/components/Form/FormItem.vue, src/style/components/form.scss, src/style/components/formGird.scss
- [form-item] 增加 marginLeftForce 属性，表示设置 margin-left 使用 important
=> 201- 07-04

src/components/SelectTable/SelectTable.vue, src/components/SimpleSelect/Block.vue
- [simple-select] 添加 remoteNoQuery 属性
=> simple-select 添加 remoteNoQuery 属性

example/views/SimpleSelect.vue, src/components/SelectTable/SelectTable.vue, src/components/SimpleSelect/Block.vue, src/components/Table/Table.vue, src/style/components/table.scss
=> fixed table bug

example/router/index.js, src/components/DatePicker/base/date-table.vue, src/components/DatePicker/base/mixin.js, src/components/DatePicker/base/month-table.vue, src/components/DatePicker/panel/Date/date-range.vue, src/components/DatePicker/panel/Date/date.vue, src/components/DatePicker/picker.vue, src/components/DatePicker/picker/date-picker.js, src/components/Form/FormItem.vue, src/components/Select/Select.vue
- [date-picker] 新增 pickMode 属性
- [time] 添加上下键盘控制时间逻辑，暂不支持 IE
- [select] 新增 validate 属性
=> 2019-07-18

src/components/SelectTable/SelectTable.vue
fixed simpleselect widthAdaption bug
=> fixed simpleselect widthAdaption bug

example/views/SimpleSelect.vue, src/components/SelectTable/SelectTable.vue, src/components/SimpleSelect/Block.vue
=> update simpleselect 

src/components/Input/Input.vue, src/components/SelectTable/SelectTable.vue, src/components/SimpleTable/Cell.vue, src/components/SimpleTable/SimpleTable.vue, src/components/SimpleTable/expand.js, src/components/Table/Table-body.vue, src/components/Table/Table.vue
=> update simpletable and table

example/views/Select.vue, example/views/Table.vue, src/components/DatePicker/picker.vue, src/components/FastDate/FastDate.vue, src/components/Form/Form.vue, src/components/Input/Input.vue, src/components/InputNumber/InputNumber.vue, src/components/Log/Log.vue, src/components/Select/Select.vue, src/components/SimpleTable/SimpleTable.vue, src/components/SimpleTable/Table-cell.vue, src/components/Table/Table-head.vue, src/components/Typefield/Typefield.vue
=> fix table/simpletable

src/style/components/input.scss, src/style/components/select.scss, src/style/components/selectTree.scss, src/style/components/tree.scss, src/style/custom.scss, src/style/mixins/button.scss, src/style/mixins/content.scss
=> add class params

src/components/SimpleMultiSelect/Block.vue, src/components/SimpleSelect/Block.vue
=> fixed simpleselect query bug

src/components/Form/FormItem.vue, src/components/Select/Dropdown.vue, src/components/SelectTable/SelectTable.vue, src/components/SimpleMultiSelect/SimpleMultiSelect.js
=> fixed multiselect bug

example/views/DatePicker.vue, src/components/DatePicker/base/confirm.vue, src/components/DatePicker/panel/Date/date-panel-mixin.js, src/components/DatePicker/panel/Date/date.vue, src/components/DatePicker/picker.vue, src/components/Form/FormItem.vue, src/components/Select/Dropdown.vue, src/util/tools.js
=> datepicker update

src/components/TransferTable/List.vue, src/components/TransferTable/Operation.vue, src/components/TransferTable/TransferTable.vue
transfer table add hide params
=> transfer table add hide params

src/components/InputNumber/InputNumber.vue, src/components/Typefield/Typefield.vue
inputnumber 修复bug，修改了changeStep的逻辑；
typefield增加整数超出位数的输入限制
=> inputnumber 修复bug，修改了changeStep的逻辑；

src/components/SimpleMultiSelect/SimpleMultiSelect.js, src/util/tools.js
=> multiselect enter fixed

example/views/EditGird.vue, example/views/MyExample.vue, example/views/Table.vue, example/views/Tabs.vue, src/components/EditGird/Gird-head.vue, src/components/EditGird/Gird-table.vue, src/components/SimpleTable/SimpleTable.vue, src/components/Tabs/Tabs.vue
=> editGird update

example/views/Backtop.vue, example/views/Form.vue, src/components/Form/Form.vue, src/style/components/radio.scss, src/style/mixins/checkbox.scss
完善了Radio单选框和checkbox复选框、h-simple-select在compareModel下变红
=> TS:201909190188  compareModel在radio checkbox不支持变红问题

example/views/GroupTable.vue, example/views/MyExample.vue, example/views/SimpleTable.vue, example/views/SimpleTreeGird.vue, src/components/SimpleTable/SimpleTable.vue, src/components/SimpleTable/mixin.js, src/components/SingleSelect/SingleSelect.vue, src/style/components/editgird.scss
singleSelect防止readonly时左右键仍可使用；
simpleTable无数据时表头最后一行溢出和外部删除数据导致全选状态未变问题
=> update singleSelect & simpleTable

src/components/DatePicker/picker.vue
date   picker.vue  isEmptyArray() []
=> date   picker.vue  isEmptyArray() []

example/views/Test.vue, src/components/DatePicker/picker.vue
=> 修复date控件 type不含range时报错问题

example/views/Page.vue, example/views/Test.vue, example/views/Test2.vue, example/views/Test4.vue, src/components/EditGird/Cell.vue, src/components/Typefield/Typefield.vue
typefield on-enter事件第一个参数不是当前值
typefield on-change 返回新老值优化
=> typefield 组件 测试修复
